# Generated by Django 2.2 on 2020-11-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0003_coffeeshop_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
