# Generated by Django 2.2 on 2020-11-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0004_coffeeshop_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeshop',
            old_name='website',
            new_name='facebook',
        ),
    ]
