# Generated by Django 2.2 on 2020-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0007_auto_20201126_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
