# Generated by Django 2.2 on 2020-12-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0008_auto_20201126_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
