# Generated by Django 2.2 on 2020-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
