# Generated by Django 2.2 on 2020-12-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0010_book_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
    ]
