# Generated by Django 2.2 on 2020-12-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0002_book_coffeeshop_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
