# Generated by Django 2.2 on 2020-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0004_auto_20201216_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
