# Generated by Django 2.2 on 2020-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
