# Generated by Django 2.2 on 2020-12-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0009_coffeeshop_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coffee_app.CoffeeShop'),
            preserve_default=False,
        ),
    ]
